name: CI

on:
  push:
    branches:
      - master
      - gha-test
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable
        - nightly

        include:
        - build: stable
          os: [self-hosted, Linux]
          toolchain: stable

        - build: nightly
          os: [self-hosted, Linux]
          toolchain: nightly

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
        targets: ${{ matrix.target }}

    - name: Run tests
      run: cargo test ${{ matrix.options }} --verbose
