name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        build:
        - linux
        - windows-msvc

        include:
        - build: linux
          os: ubuntu-latest
          install-deps: sudo apt-get install -y gcc-multilib
          toolchain: stable
          targets: x86_64-unknown-linux-gnu i686-unknown-linux-gnu
          configs: linux64 linux32

        - build: windows-msvc
          os: windows-latest
          toolchain: stable
          targets: x86_64-pc-windows-msvc i686-pc-windows-msvc
          configs: win64 win32

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: ${{ matrix.install-deps }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
        targets: ${{ matrix.targets }}

    - name: Build
      run: python build.py ${{ matrix.configs }}

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: "dist/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
